artifact_uri: file:///workspace/weighted_mtp/mlruns/531320661814715863/16c5a26e560b40f6a4fa8760e7ddf8fb/artifacts
end_time: 1764820406851
entry_point_name: ''
experiment_id: '531320661814715863'
lifecycle_stage: active
run_id: 16c5a26e560b40f6a4fa8760e7ddf8fb
run_name: eval_gsm8k_checkpoint_final
source_name: ''
source_type: 4
source_version: ''
start_time: 1764819139323
status: 3
tags: []
user_id: root
