artifact_uri: file:///Users/wesley/Desktop/wooshikwon/weighted_mtp/mlruns/869427667672898361/a94647505a624d2fa1e8a3f2a0c3bc85/artifacts
end_time: 1764550984047
entry_point_name: ''
experiment_id: '869427667672898361'
lifecycle_stage: active
run_id: a94647505a624d2fa1e8a3f2a0c3bc85
run_name: lora-critic-lambda-0.995-final
source_name: ''
source_type: 4
source_version: ''
start_time: 1764535240836
status: 3
tags: []
user_id: wmtp_admin
