artifact_uri: file:///workspace/weighted_mtp/mlruns/519782836693531210/93ceed91a48345f78e9b2457f39c70f0/artifacts
end_time: null
entry_point_name: ''
experiment_id: '519782836693531210'
lifecycle_stage: active
run_id: 93ceed91a48345f78e9b2457f39c70f0
run_name: ultimate-ref-tuning-400k-32rank
source_name: ''
source_type: 4
source_version: ''
start_time: 1764887049331
status: 1
tags: []
user_id: root
