artifact_uri: file:///Users/wesley/Desktop/wooshikwon/weighted_mtp/mlruns/869427667672898361/59b1ab9cbed14b1fbe75ee091d2f75c8/artifacts
end_time: 1764200209729
entry_point_name: ''
experiment_id: '869427667672898361'
lifecycle_stage: active
run_id: 59b1ab9cbed14b1fbe75ee091d2f75c8
run_name: verifiable-pairwise
source_name: ''
source_type: 4
source_version: ''
start_time: 1764183132817
status: 3
tags: []
user_id: wmtp_admin
