artifact_uri: file:///workspace/weighted_mtp/mlruns/531320661814715863/820f4ecbbb0d46cea82cd3e864cdf7d3/artifacts
end_time: null
entry_point_name: ''
experiment_id: '531320661814715863'
lifecycle_stage: active
run_id: 820f4ecbbb0d46cea82cd3e864cdf7d3
run_name: eval_gsm8k_checkpoint_final
source_name: ''
source_type: 4
source_version: ''
start_time: 1764826059351
status: 1
tags: []
user_id: root
