artifact_uri: file:///workspace/weighted_mtp/mlruns/519782836693531210/0d0226a952c64bae9128e4962479227f/artifacts
end_time: null
entry_point_name: ''
experiment_id: '519782836693531210'
lifecycle_stage: active
run_id: 0d0226a952c64bae9128e4962479227f
run_name: last-final-value-model-stratified-MC
source_name: ''
source_type: 4
source_version: ''
start_time: 1764941156163
status: 1
tags: []
user_id: root
