artifact_location: file:///Users/wesley/Desktop/wooshikwon/weighted_mtp/mlruns/415604424622996807
creation_time: 1764466782517
experiment_id: '415604424622996807'
last_update_time: 1764466782517
lifecycle_stage: active
name: weighted-mtp/production
