artifact_uri: file:///Users/wesley/Desktop/wooshikwon/weighted_mtp/mlruns/869427667672898361/4eeb155d0a244757a04f87a3bb1fe40c/artifacts
deleted_time: 1764397047594
end_time: 1764060101864
entry_point_name: ''
experiment_id: '869427667672898361'
lifecycle_stage: deleted
run_id: 4eeb155d0a244757a04f87a3bb1fe40c
run_name: critic-pretrain-linear-final
source_name: ''
source_type: 4
source_version: ''
start_time: 1764055696375
status: 3
tags: []
user_id: wmtp_admin
