artifact_uri: file:///workspace/weighted_mtp/mlruns/519782836693531210/6f6562e73fb74205b2231a4ef2c3bb15/artifacts
end_time: null
entry_point_name: ''
experiment_id: '519782836693531210'
lifecycle_stage: active
run_id: 6f6562e73fb74205b2231a4ef2c3bb15
run_name: ultimate-value-model-400k-32rank
source_name: ''
source_type: 4
source_version: ''
start_time: 1764905691303
status: 1
tags: []
user_id: root
