artifact_uri: file:///workspace/weighted_mtp/mlruns/531320661814715863/a148cb9d4cb04f949cbfa91e1c544471/artifacts
end_time: null
entry_point_name: ''
experiment_id: '531320661814715863'
lifecycle_stage: active
run_id: a148cb9d4cb04f949cbfa91e1c544471
run_name: eval_codecontests_checkpoint_final
source_name: ''
source_type: 4
source_version: ''
start_time: 1764831467716
status: 1
tags: []
user_id: root
