artifact_uri: file:///workspace/weighted_mtp/mlruns/519782836693531210/a31449cf313c4258b7a23acaad4fe88b/artifacts
end_time: null
entry_point_name: ''
experiment_id: '519782836693531210'
lifecycle_stage: active
run_id: a31449cf313c4258b7a23acaad4fe88b
run_name: last-final-value-model-stratified
source_name: ''
source_type: 4
source_version: ''
start_time: 1764921299274
status: 1
tags: []
user_id: root
