artifact_uri: file:///workspace/weighted_mtp/mlruns/531320661814715863/acb438972b064a31b1e9a83ed92ad946/artifacts
end_time: null
entry_point_name: ''
experiment_id: '531320661814715863'
lifecycle_stage: active
run_id: acb438972b064a31b1e9a83ed92ad946
run_name: eval_gsm8k_checkpoint_final
source_name: ''
source_type: 4
source_version: ''
start_time: 1764903134981
status: 1
tags: []
user_id: root
