artifact_uri: file:///workspace/weighted_mtp/mlruns/0/317ea653d53e4e9996fc90a5c2bb5e00/artifacts
end_time: null
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 317ea653d53e4e9996fc90a5c2bb5e00
run_name: eval_mbpp_checkpoint_epoch_1.80
source_name: ''
source_type: 4
source_version: ''
start_time: 1764738579441
status: 1
tags: []
user_id: root
