artifact_uri: file:///workspace/weighted_mtp/mlruns/519782836693531210/5cae1bb1f33e488a82753d0b1acee01b/artifacts
end_time: null
entry_point_name: ''
experiment_id: '519782836693531210'
lifecycle_stage: active
run_id: 5cae1bb1f33e488a82753d0b1acee01b
run_name: ultimate-value-model
source_name: ''
source_type: 4
source_version: ''
start_time: 1764755454983
status: 1
tags: []
user_id: root
